swagger: '2.0'
info:
  version: 1.0.0
  title: IoF Monitoring
  description: Monitoring Service for IoF
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /
paths:
  /configurations:
    get:
      description: |
        	Get a list of all configurations for all aquariums, including unconfigured aquariums (id only)
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Configuration'
      tags:
        - configuration
  /configurations/{aquarium-id}:
    get:
      description: |
        	Get a single configuration
      operationId: getConfig
      parameters:
        - 
          name: aquarium-id
          in: path
          description: Mac address of the controller
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Configuration'
        404:
          description: Configuration not found
      tags:
        - configuration
    post:
      description: edit an existing configuration
      operationId: editConfig
      parameters:
        -
          name: aquarium-id
          in: path
          description: Mac address of the controller
          required: true
          type: string
        -
          name: configuration
          in: body
          description: Configuration of the aquarium
          required: true
          schema:
            $ref: '#/definitions/Configuration'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful changed the config
        404:
          description: Configuration not found
        500:
          description: Error processing the config
      tags:
        - configuration
    delete:
      description: Delete an existing configuration
      operationId: deleteConfig
      parameters:
        -
          name: aquarium-id
          in: path
          description: Mac address of the controller
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful deleted the config
        404:
          description: Configuration not found
        500:
          description: Error deleting the config
      tags:
        - configuration
      
  /aquariums:
    get:
      description: |
        		Get a list of all offices and aquariums
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Aquarium'
      tags:
        - aquarium
  /aquariums/{aquarium-id}:
    get:
      description: |
        		Get the state of a specific aquarium
      parameters:
        -
          name: aquarium-id
          in: path
          description: Mac address of the controller
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Aquarium'
        404:
          description: Aquarium not found
      tags:
          - aquarium
            
definitions:
  
  Configuration:
    type: object
    required:
      - aquarium-id
    properties:
      aquarium-id:
        type: string
        description: Mac address of the controller
        example: "8f:21:ab:9c:73:4c"
      fish-mapping:
        type: array
        items:
          $ref: '#/definitions/FishMapping'
      office:
        $ref: '#/definitions/Office'
        
  FishMapping:
    type: object
    required:
      - fish-id
    properties:
      fish-id:
        type: string
        description: id/pin of the fish
        example: "1"
      office:
        $ref: '#/definitions/Office'
  Aquarium:
    type: object
    required:
      - aquarium-id
      - office
    properties:
      aquarium-id:
        type: string
        description: mac-address of the controller
        example: "8f:21:ab:9c:73:4c"
      office:
        $ref: '#/definitions/Office'
      status:
        type: string
        description: current status of the aquarium
        example: OK
  Office:
    type: object
    required:
      - office-id
      - city
      - country
    properties:
      office-id:
        type: string
        description: id of the office
        example: "1"
      city:
        type: string
        description: city the office is located
        example: "Berne"
      country:
        type: string
        description: two letter country code of the office
        example: "CH"